version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_container
    ports:
      - "8000:8000"
    volumes:
     - /home/ubuntu/docker-fastapi-test/dockerized_app/shared_data:/app/app/data
    restart: always


